watch:
  directories:
    - app
    - routes
    - database
    - config
    - src
    - tests
  fileMask: "*.php"
notifications:
  passingTests: false
  failingTests: false
phpunit:
  binaryPath: vendor/bin/phpunit
  arguments: "--stop-on-failure"
  timeout: 180
